name = "form-relay"
main = "src/worker.ts"
compatibility_date = "2025-01-09"

# Custom domain will be configured in Cloudflare Dashboard
# Go to Workers & Pages → form-relay → Settings → Custom Domains

# Environment variables (set these via wrangler secret put)
# Required (sensitive information only):
# - MAILGUN_API_KEY
# - MAILGUN_DOMAIN (e.g., "mail.tanuj.xyz")
#
# Form configurations are in repository files:
# - config/forms.json (form-specific settings)
# - config/defaults.json (default fallback settings)

# Optional: bindings (currently commented out)
# [[kv_namespaces]]
# binding = "RATE_KV"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[d1_databases]]
# binding = "FORMS_D1"
# database_name = "forms"
# database_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"

[observability.logs]
enabled = true